# Generated by Django 5.0.2 on 2024-10-19 05:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_atencion', models.DateField()),
                ('hora_atencion', models.TimeField()),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'atencion',
                'verbose_name_plural': 'atenciones',
                'db_table': 'atencion',
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'box',
                'verbose_name_plural': 'boxes',
                'db_table': 'boxes',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('especialidad', models.CharField(max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='hospital/medicos')),
            ],
            options={
                'verbose_name': 'medico',
                'verbose_name_plural': 'medicos',
                'db_table': 'medicos',
            },
        ),
    ]
