# Generated by Django 5.0.2 on 2024-03-16 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservaatencion',
            options={'verbose_name': 'reserva de atencion', 'verbose_name_plural': 'reservas de atencion'},
        ),
        migrations.AlterModelTable(
            name='reservaatencion',
            table='reserva_atencion',
        ),
    ]
