# Generated by Django 5.0.2 on 2024-10-19 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medico',
            name='box',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.box'),
        ),
        migrations.AddField(
            model_name='medico',
            name='usuario',
            field=models.ManyToManyField(blank=True, through='hospital.Atencion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atencion',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.medico'),
        ),
        migrations.AddConstraint(
            model_name='atencion',
            constraint=models.UniqueConstraint(fields=('medico', 'fecha_atencion', 'hora_atencion'), name='unique_reserva_atencion'),
        ),
    ]
