# Generated by Django 5.0.2 on 2024-03-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_reservaatencion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='nombre_completo',
        ),
        migrations.AddField(
            model_name='medico',
            name='apellido',
            field=models.CharField(default='-', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medico',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='hospital/medicos'),
        ),
        migrations.AddField(
            model_name='medico',
            name='nombre',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
