# Generated by Django 5.0.2 on 2024-03-18 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_remove_medico_nombre_completo_medico_apellido_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservaatencion',
            name='atencionmedica',
        ),
        migrations.RemoveField(
            model_name='reservaatencion',
            name='usuario',
        ),
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_atencion', models.DateField()),
                ('hora_atencion', models.TimeField()),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.medico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'atencion',
                'verbose_name_plural': 'atenciones',
                'db_table': 'atencion',
            },
        ),
        migrations.AddField(
            model_name='medico',
            name='usuario',
            field=models.ManyToManyField(blank=True, through='hospital.Atencion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('medico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hospital.medico')),
            ],
            options={
                'verbose_name': 'box',
                'verbose_name_plural': 'boxes',
                'db_table': 'boxes',
            },
        ),
        migrations.DeleteModel(
            name='AtencionMedica',
        ),
        migrations.DeleteModel(
            name='ReservaAtencion',
        ),
        migrations.AddConstraint(
            model_name='atencion',
            constraint=models.UniqueConstraint(fields=('medico', 'fecha_atencion', 'hora_atencion'), name='unique_reserva_atencion'),
        ),
    ]
