# Generated by Django 5.0.2 on 2024-04-09 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_remove_box_medico_medico_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='box',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.box'),
        ),
    ]
