# Generated by Django 5.0.2 on 2024-04-09 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_alter_medico_box'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='box',
        ),
        migrations.AddField(
            model_name='box',
            name='medico',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.medico'),
        ),
    ]
