# Generated by Django 5.0.2 on 2024-03-15 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='rut',
            new_name='username',
        ),
    ]
