# Generated by Django 5.0.2 on 2024-03-15 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_rut_usuario_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
    ]
